<a href="https://colab.research.google.com/github/kiransree2002/NLP_FakeNews-Classification/blob/main/Model/FakeNews(Classification)_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
import pandas as pd

# Reading Dataset

In [20]:
train_df = pd.read_csv("/content/train (2).csv",sep=None , on_bad_lines="skip")
train_df.head()

/tmp/ipykernel_507/3837114398.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  train_df = pd.read_csv("/content/train (2).csv",sep=None , on_bad_lines="skip")

,Unnamed: 0,title,text,label
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1.0
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1.0
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0.0
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1.0
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0.0

In [21]:
eval_df = pd.read_csv("/content/evaluation.csv",sep=None , on_bad_lines="skip")
train_df.head()

/tmp/ipykernel_507/3709412326.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  eval_df = pd.read_csv("/content/evaluation.csv",sep=None , on_bad_lines="skip")

,Unnamed: 0,title,text,label
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1.0
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1.0
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0.0
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1.0
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0.0

In [22]:
test_df = pd.read_csv("/content/test (1).csv",sep=None , on_bad_lines="skip")
train_df.head()

/tmp/ipykernel_507/804740516.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  test_df = pd.read_csv("/content/test (1).csv",sep=None , on_bad_lines="skip")

,Unnamed: 0,title,text,label
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1.0
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1.0
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0.0
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1.0
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0.0

# EDA

## EDA for Training dataset

In [25]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1213 entries, 0 to 1212
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1213 non-null   int64
 1   title       1213 non-null   object
 2   text        1213 non-null   object
 3   label       1212 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 38.0+ KB

In [26]:
train_df.head()

,Unnamed: 0,title,text,label
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1.0
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1.0
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0.0
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1.0
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0.0

In [33]:
train_df.shape

(1213, 4)

## EDA for Evaluation dataset

In [27]:
eval_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1248 non-null   int64
 1   title       1248 non-null   object
 2   text        1248 non-null   object
 3   label       1248 non-null   int64
dtypes: int64(2), object(2)
memory usage: 39.1+ KB

In [28]:
eval_df.head()

,Unnamed: 0,title,text,label
0,0,"Sanders back in U.S. Senate, blasts 'coloniali...",WASHINGTON (Reuters) - Democratic U.S. preside...,1
1,1,Kremlin: Syria peoples' congress being 'active...,MOSCOW (Reuters) - A proposal to convene a con...,1
2,2,Oregon Cop Convicted Of Shattering Biker’s Co...,"In a baffling fit of rage, an Oregon State Pol...",0
3,3,Twitter Erupts With Glee Over #CruzSexScandal...,The last thing any politician running for the ...,0
4,4,MUST WATCH VIDEO: Obama Tries To Trash Trump B...,This is too good to miss! Mr. Teleprompter did...,0

In [32]:
eval_df.shape

(1248, 4)

## EDA for Test dataset

In [29]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1195 entries, 0 to 1194
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1195 non-null   int64
 1   title       1195 non-null   object
 2   text        1195 non-null   object
 3   label       1194 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 37.5+ KB

In [30]:
test_df.head()

,Unnamed: 0,title,text,label
0,0,"Live from New York, it's a Trump-Clinton remat...",NEW YORK (Reuters) - Veteran actor and frequen...,1.0
1,1,Catalan separatists to lose majority in tight ...,BARCELONA (Reuters) - Catalonia s independence...,1.0
2,2,North Carolina governor concedes election to D...,"WINSTON-SALEM, N.C. (Reuters) - North Carolina...",1.0
3,3,Draft Senate Iran legislation sets tough new U...,WASHINGTON (Reuters) - Draft legislation respo...,1.0
4,4,California governor taps U.S. Representative B...,"SACRAMENTO, Calif. (Reuters) - California Gove...",1.0

In [31]:
test_df.shape

(1195, 4)

# Preprocessing